/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recursionapp;

/**
 *
 * @author Gavin Mulvany
 */
public class RecursionGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecursionGUI
     */
    
    Palindrome pal = new Palindrome();
    Reverse rev = new Reverse();
    TwoPower two = new TwoPower();
    XPowerY xPow = new XPowerY();
    
    
    public RecursionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTA = new javax.swing.JTextArea();
        exitBtn = new javax.swing.JButton();
        xPowBtn = new javax.swing.JButton();
        xTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        yTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        revTF = new javax.swing.JTextField();
        revBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        twoTF = new javax.swing.JTextField();
        twoBtn = new javax.swing.JButton();
        palTF = new javax.swing.JTextField();
        palBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTA.setColumns(20);
        mainTA.setRows(5);
        jScrollPane1.setViewportView(mainTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 292, 151));

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 69, 34));

        xPowBtn.setText("X ^ Y");
        xPowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(xPowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 30));

        xTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xTFActionPerformed(evt);
            }
        });
        getContentPane().add(xTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 90, -1));

        jLabel1.setText("X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 10, -1));

        jLabel2.setText("Y");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 30, -1));
        getContentPane().add(yTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, -1));

        jLabel3.setText("Reverse:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 70, 30));
        getContentPane().add(revTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 80, -1));

        revBtn.setText("Reverse");
        revBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revBtnActionPerformed(evt);
            }
        });
        getContentPane().add(revBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 100, 30));

        jLabel4.setText("2 ^ : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 30));
        getContentPane().add(twoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, -1));

        twoBtn.setText("2 ^ num");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 90, 30));
        getContentPane().add(palTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 120, 30));

        palBtn.setText("Check Palindrome");
        palBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palBtnActionPerformed(evt);
            }
        });
        getContentPane().add(palBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 150, 30));

        jLabel5.setText("Enter String:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void xTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xTFActionPerformed
        
    }//GEN-LAST:event_xTFActionPerformed

    
    private void print(String msg){
        mainTA.setText(msg);
    }
    
    
    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
      
        int num = Integer.parseInt(twoTF.getText());
        
        
        print(two.calc(num)+"");
        
        
    }//GEN-LAST:event_twoBtnActionPerformed

    private void xPowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPowBtnActionPerformed
        
        int x = Integer.parseInt(xTF.getText());
        int y = Integer.parseInt(yTF.getText());
        
        print(xPow.calc(x,y)+"");
        
    }//GEN-LAST:event_xPowBtnActionPerformed

    private void revBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revBtnActionPerformed
        
        String in = revTF.getText();
        
        print(rev.reverse(in));
        
    }//GEN-LAST:event_revBtnActionPerformed

    private void palBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palBtnActionPerformed
        String in = palTF.getText();
        
        print(pal.isPalindrome(in)+"");
                
    }//GEN-LAST:event_palBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecursionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecursionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainTA;
    private javax.swing.JButton palBtn;
    private javax.swing.JTextField palTF;
    private javax.swing.JButton revBtn;
    private javax.swing.JTextField revTF;
    private javax.swing.JButton twoBtn;
    private javax.swing.JTextField twoTF;
    private javax.swing.JButton xPowBtn;
    private javax.swing.JTextField xTF;
    private javax.swing.JTextField yTF;
    // End of variables declaration//GEN-END:variables
}
